packages:
  - '.'
  - '../widgets/interactives/rich-text'
  - '../widgets/interactives/video'
  - '../widgets/assessments/single-question'
  - '../widgets/assessments/open-response'
  - '../widgets/questions/meqn'
  - '../widgets/questions/fib'
  - '../widgets/questions/rich-text'
  - '../widgets/questions/plain-text'
  - '../widgets/shared/assessment-core'
  - '../widgets/shared/scoring-engine'
  - '../widgets/inputs/wiris-equation'
  - '../widgets/inputs/froala-rich-text'
  - '../widgets/shared/theme'
